### ISSUE TITLE
[suggestion]this plugin can not support query imports function

### ISSUE THREAD

**Issue by zhefox** [Accenture/VulFi#11]
Some functions are called Kennel32 functions, vulfi does not support retrieval of these imported functions

**Comment by Martyx00** [comment]
Hello, is it possible to share an example binary fike? Thanks.

**Comment by zhefox** [comment]
such as 
![image](https://github.com/Accenture/VulFi/assets/77232781/b22c9269-2785-4b16-882a-91af21af6278)

![image](https://github.com/Accenture/VulFi/assets/77232781/687c78e5-4fa8-40e5-8e67-132513b0b80d)


The external link import function called by this method cannot be collected even if its name is specified in the custom rule

**Comment by Martyx00** [comment]
If you can share the binary itself, please do so. Otherwise, I wll try to find some example myself. Thanks for reporting.

**Comment by zhefox** [comment]
you can use any system32/*.dll to test . Of course I can also give you a  file
[adllfile.zip](https://github.com/Accenture/VulFi/files/12460327/adllfile.zip)

**Comment by zhefox** [comment]
oh ,I think I solved this problem, there is a problem with my rule rule, I can't directly "GetModuleHandleW", I need to give him the full name "__imp_GetModuleHandleW" in the .idata section

**Comment by zhefox** [comment]
```

        # For each import
        number_of_imports = idaapi.get_import_module_qty()
        for i in range(0, number_of_imports):
            idaapi.enum_import_names(i, imports_callback)
```
No wonder I found that you clearly wrote related methods when I checked your source code

**Comment by zhefox** [comment]
thanks！

**Comment by zhefox** [comment]
I will close my issue, thank you very much for your reply
