### ISSUE TITLE
[problem] “param[1].used_in_call_before()“ method has something wrong

### ISSUE THREAD

**Issue by zhefox** [Accenture/VulFi#13]
When I write the rule like this：
```
(not param[0].used_in_call_before(['__imp_wcscat_s']) and not param[0].is_constant())
```
it is not valid when i add like this：
``` 
(not param[0].used_in_call_before(['__imp_wcscat_s','wcscat_s']) and not param[0].is_constant())
```

how can i construct gramma

![image](https://github.com/Accenture/VulFi/assets/77232781/42d7b5b1-33f2-4219-98ce-816a0c3dd4bd)

and when i use 
```
 (not param[0].used_in_call_before(['__imp_wcscat_s']) and not param[0].is_constant()) 

or 

(not param[0].used_in_call_before(['wcscat_s']) and not param[0].is_constant())
```

He didn't filter out the current buffer being used as a parameter of wcscat_s for me

**Comment by zhefox** [comment]
even i choose GetSystemDirectoryW()
![image](https://github.com/Accenture/VulFi/assets/77232781/ff4d06ab-06e4-4ec7-b4c6-e4af2c977ea9)

Neither can it

**Comment by Martyx00** [comment]
Is there an error or the rule just fails to detect the occurance that you are expecing?

**Comment by zhefox** [comment]
yes，I hope to filter out the parts of the buffer that were used by GetSystemDirectoryW() before being used as a parameter in a function, but obviously, he cannot

**Comment by zhefox** [comment]
It is possible to give an example with or without checking strlen， but im not sure

**Comment by Martyx00** [comment]
Can you share the binary file?

**Comment by zhefox** [comment]
C:\\Windows\System32\InkEd.dll is a simple binary

**Comment by zhefox** [comment]
you can try to 
```
[
    {
        "name": "aaaa",
        "function_names":[
            "__imp_LoadLibraryW"
           

        ],
        "wrappers":false,
        "mark_if":{
            "High":"(not param[0].used_in_call_before(['__imp_GetSystemDirectoryW']) and not param[0].is_constant())",
            "Medium":"False",
            "Low": "False"
        }
    }


]
```

**Comment by Martyx00** [comment]
This should be fixed with: https://github.com/Accenture/VulFi/commit/03df8fb1c89251fbf1ef75258abb2648fb13cfa6 
Please verify that it behaves as expected.

**Comment by zhefox** [comment]
You're so good, it looks like it can be done

**Comment by zhefox** [comment]
Another question I have is that when I check whether the current parameter is called by the specified function, can I also judge whether the parameter of the check function is equal to or not equal to the specified value?

**Comment by Martyx00** [comment]
You can get `.number_value()` or `.string_value()` for any parameters that are constants in the current XREF. Parameters that are checked for calls with `.used_in_call_<before|after>()` can only be in form of a variable and thus cannot be checked for any specific value.
