### ISSUE TITLE
[suggestion] Add the feature of highlighting the results list.

### ISSUE THREAD

**Issue by zhefox** [Accenture/VulFi#14]
If possible, different Status can be highlighted differently. I think this may make it easier to analyze when there is a lot of data to be reviewed, without the need to export to Excel and manually set highlighting rules in the spreadsheet.

**Comment by Martyx00** [comment]
Try this one: https://github.com/Accenture/VulFi/commit/b9049b6eb8e27053a2fd0f2abcb936c2b54bf7d0

**Comment by zhefox** [comment]
wow!The efficiency is so high!

**Comment by zhefox** [comment]
But I think maybe he didn't succeed in coloring the corresponding danger levels in the list of IDA.

**Comment by Martyx00** [comment]
The coloring is applied to the status. Vulnerable is red, Suspicious is orange and False Positive is gray. I dont think severity is accurate enough to be considered that important. Furthermore the table could be sorted by it so you will have the issues grouped by the category.

**Comment by zhefox** [comment]
![image](https://github.com/Accenture/VulFi/assets/77232781/0938bd19-dbfc-4f99-8502-af33e2480033)
maybe it still no color

**Comment by Martyx00** [comment]
Could you try on the `dev` branch? THe highlight works for me there (with couple new features which are not yet well tested :) )
![image](https://github.com/Accenture/VulFi/assets/20481897/19c09501-f4af-4034-9612-8b840b4184ba)

**Comment by zhefox** [comment]
I think I should try the dev branch now.
Wait for me for a moment.

**Comment by zhefox** [comment]
This is a strange thing, my 7.7 is still not working.
I was wondering if it was because of my theme, so I reverted it back to the original theme, but it still doesn't seem to be functioning properly. I don't know where it is conflicting with my settings.

**Comment by zhefox** [comment]
![image](https://github.com/Accenture/VulFi/assets/77232781/b555acca-8560-431e-a526-7f945e8df353)
I am testing on IDA 7.6, but it still doesn't seem to work properly. Do I need some additional settings? For example, what settings should I enable?

**Comment by Martyx00** [comment]
It could be the version, I have the latest 8.3. It may be that this feature was added in 8.X.

**Comment by zhefox** [comment]
Oh, I really envy version 8.x, but I only have version 7. I am very sad. Maybe it can also be compatible with version 7?

**Comment by Martyx00** [comment]
I do not have an active license for pre 8.X so I cannot test it. I am also testing it in Linux version of IDA so that may also be a difference,

**Comment by zhefox** [comment]
I am using Windows, maybe the color recognition on its two sides is different? I guess it might not be.
Where can I find the relevant development documentation for version 7.7? I believe it might be similar, but I just need to integrate some methods from idaapi. I really hope I can make use of it.

**Comment by zhefox** [comment]
I tested the colleague's 8.3 on Windows and it did display, so it can be confirmed that it is a version problem. I am very sad :(.

**Comment by zhefox** [comment]
https://www.hex-rays.com/products/ida/support/idapython_docs/ida_kernwin.html#ida_kernwin.Choose.OnGetLineAttr

I think this configuration seems to be fine. I am planning to debug the output to see if there is an issue with the color codes.

**Comment by zhefox** [comment]
The color code is not the reason for the problem. I still need to search for the old documents.

**Comment by zhefox** [comment]
I did not see the definition of the function "OnGetLineAttr" in the "ida_kernwin.py" file of IDA 7.7. It is possible that it is not supported. I have tried to modify it in order to add support for it.

**Comment by zhefox** [comment]
I think I need to study lighthouse's CSS in order to modify it, so that it can display colors in a similar way as its method. I need to find some free time for that, but for now, I need to finish my work first.

**Comment by Martyx00** [comment]
I will close this issue as backporting IDA API is not part of this tool. Good luck with that anyway :)
