### ISSUE TITLE
About the problem that the plug-in cannot run in ida Pro 9.0

### ISSUE THREAD

**Issue by p1yang** [Accenture/VulFi#19]
Ida Pro 9.0 modified part of the pythonapi, causing vuifi to fail to run. I modified some of the code to make it possible to run.
```
add import ida_ida
line 111：comment on this line
line 112:  change to   if ida_ida.inf_is_64bit():
line 114:  change to  elif ida_ida.inf_is_32bit_exactly():
line 119:  change to  self.endian = "big" if ida_ida.inf_is_be() else "little"
```

**Comment by zhefox** [comment]
Great, that's correct, but it looks like some of the loop's retrieval still has adaptation issues

**Comment by nmweizi** [comment]
During the search process, IDA crashes and exits.

**Comment by p1yang** [comment]
> During the search process, IDA crashes and exits.

I haven't encountered the problem you mentioned for the time being. wait for the author to update.

**Comment by phosmium** [comment]
Yea, well. Some of the code takes up a really big amount of time still.

As example, the function at https://github.com/Accenture/VulFi/blob/main/vulfi.py#L1495
`for function in idautils.Functions():` can take really long on big IDBs, resulting in lags/freezes when right-clicking.

**Comment by Martyx00** [comment]
Pull request was merged.
